config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users do 
    resources :gossips 
  end


  # get '/user/:id', to: 'user#show', as: 'user'
  # get '/gossip/:id', to: 'gossip#show', as: 'gossip'
  get 'welcome/:id', to: 'welcome#index'
  get '/team', to: 'team#index'
  get '/contact', to: 'contact#index'
  root "homes#index"
end

app/models/application_record.1.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name, :zip_code, presence: true

    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, length: { in: 3..14}, presence: true
    validates :content, presence: true

    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, presence: true
    # Validation de l'email par une présence obligatoire et unique avec un format particulier
    validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    belongs_to :city
    has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    def index
        @gossips = Gossip.all
      end
    
      def show
        @gossip = Gossip.find(params[:id])
      end
    
      # Méthode qui permet de créer un nouveau gossip
      def new
        @gossip = Gossip.new
      end
    
      # Méthode qui permet de créer un nouveau gossip avec les params récupéré dans le formulaire de la vue new de gossip
      def create
        @gossip = Gossip.new(:user_id => params[:user_id], :title => params[:title], :content => params[:content])
        if @gossip.save
        redirect_to root_path
        else
        render 'new'
        end
      end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
        @gossips = Gossip.all
        @users = User.all
      end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
  
    # Méthode qui permet d'afficher un user en particulier et ça city
    def show
      @user = User.find(params[:id])
      @city_user = @user.city_id
      @city = City.find(@city_user)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<h1>Contact:</h1>
<p>Pour contacter l'équipe Bunker il faut dire trois fois devant un mirroir "Team Bunker, Team Bunker, Team Bunker" ;-) 

app/views/gossips/index.html.erb
<h1>Gossip#index</h1>
<p>Find me in app/views/gossip/index.html.erb</p>

app/views/gossips/new.html.erb
<%= form_with url: user_gossips_path do |form| %>
  <%= form.text_field :title %>
  <%= form.text_field :content %>
  <%= form.submit %>
<% end %>


<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/gossips/show.html.erb
<!-- La vue d'un gossip -->

<!-- Titre de la vue d'un gossip avec le numéro du gossip -->
<h1>Gossip <%= params[:id] %></h1>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h3 class="card-title">Title : 
    <%= @gossip.title %></h3>
    <h5 class="card-title">Content:</h5>
    <p class="card-text"><%= @gossip.content %></p>
  </div>
</div>

app/views/home/index.html.erb
<!-- Vue de la page d'accueil de l'appication -->
<h1>HI <%= params[:id] %> ! WELCOME TO THE GOSSIPS CENTER :</h1>

<!-- Boucle qui parcours tous les gossips -->
<% @gossips.each do |gossip|%>
<!-- Affichage des information de chaques gossips -->
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">AUTHOR : 
            <% @user_first_name = @users.find(gossip.user_id) %>
            <%= @user_first_name.first_name %></h5>
            <p class="card-text"><%= gossip.title %></p>

<!-- Liens vers les différentes pages qui dépendent du gossip -->
            <%= link_to "Go to this Gossip Page", user_gossip_index_path(user_id: gossip.user_id), :class => "btn btn-primary"%>
            
            <%= link_to "Go to this User Page", user_path(id: gossip.user_id), :class => "btn btn-primary" %>

            <%= link_to "New Gossip", new_user_gossip_path(user_id: gossip.user_id), :class => "btn btn-primary"%>
        </div>
    </div>
<% end %>

app/views/homes/index.html.erb
<!-- Vue de la page d'accueil de l'appication -->
<h1>HI <%= params[:id] %> ! WELCOME TO THE GOSSIPS CENTER :</h1>

<!-- Boucle qui parcours tous les gossips -->
<% @gossips.each do |gossip|%>
<!-- Affichage des information de chaques gossips -->
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">AUTHOR : 
            <% @user_first_name = @users.find(gossip.user_id) %>
            <%= @user_first_name.first_name %></h5>
            <p class="card-text"><%= gossip.title %></p>

<!-- Liens vers les différentes pages qui dépendent du gossip -->
            <%= link_to "Go to this Gossip Page", user_gossips_path(user_id: gossip.user_id), :class => "btn btn-primary"%>
            
            <%= link_to "Go to this User Page", user_path(id: gossip.user_id), :class => "btn btn-primary" %>

            <%= link_to "New Gossip", new_user_gossip_path(user_id: gossip.user_id), :class => "btn btn-primary"%>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjectV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/journal/bootstrap.min.css">  
  </head>

  <body>
  
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <%= link_to "HOME", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "TEAM", teams_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "CONTACT", contact_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </nav>

    <%= yield %>

  </body>

app/views/user/show.html.erb
<!-- Titre de la vue avec du user -->
<h1>User Page</h1>

    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">First name:</h5>
        <p class="card-text"><%= @user.first_name %></p>
        <h5 class="card-title">Last name:</h5>
        <p class="card-text"><%= @user.last_name %></p>
        <h5 class="card-title">Description:</h5>
        <p class="card-text"><%= @user.description %></p>
        <h5 class="card-title">E-mail:</h5>
        <p class="card-text"><%= @user.email %></p>
        <h5 class="card-title">Age:</h5>
        <p class="card-text"><%= @user.age %></p>
        <h5 class="card-title">City:</h5>
        <p class="card-text"><%= @city.name %></p>


      </div>
    </div>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/show.html.erb
<!-- Titre de la vue avec du user -->
<h1>User Page</h1>

    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">First name:</h5>
        <p class="card-text"><%= @user.first_name %></p>
        <h5 class="card-title">Last name:</h5>
        <p class="card-text"><%= @user.last_name %></p>
        <h5 class="card-title">Description:</h5>
        <p class="card-text"><%= @user.description %></p>
        <h5 class="card-title">E-mail:</h5>
        <p class="card-text"><%= @user.email %></p>
        <h5 class="card-title">Age:</h5>
        <p class="card-text"><%= @user.age %></p>
        <h5 class="card-title">City:</h5>
        <p class="card-text"><%= @city.name %></p>


      </div>
    </div>

app/views/welcome/index.html.erb
<h1>Welcome <%= params[:id] %> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>